### ISSUE TITLE
Custom DPI ?

### ISSUE THREAD

**Issue by ChameleonScales** [oxplot/svglinkify#1]
It would be great if we could set a custom DPI for rasterization.

**Comment by oxplot** [comment]
Thanks. Added in [v0.3](https://github.com/oxplot/svglinkify/releases/tag/v0.3)

**Comment by ChameleonScales** [comment]
Wow, that was fast !
What would be the command?

**Comment by oxplot** [comment]
`-dpi` — see the usage text (ie run `svglinkify -h`) for details

**Comment by ChameleonScales** [comment]
Thanks, it works great. Thank you for this extension
