### ISSUE TITLE
Unable to open output PDF in Adobe Reader

### ISSUE THREAD

**Issue by sunjerry019** [oxplot/svglinkify#2]
Hi there, not sure if you still actively maintain this but I tried to use your script and encountered the following problem:

1. Create a test svg with some test link 
2. `svglinkify drawing.svg drawing.pdf`
3. 
    a. Opens fine in Okular, links are clickable
    b. Send to friend who uses Windows/Adobe Acrobat and it only shows a white box

![capture](https://user-images.githubusercontent.com/9073779/51812971-beca4a80-22ee-11e9-9b3a-8e58d21f9e9b.png)

I have reproduced it on my own Windows installation as well so it's not an isolated issue.

Files are as attached:
[drawing.zip](https://github.com/oxplot/svglinkify/files/2801276/drawing.zip)

Platform: Linux x86_64
OS: Arch Linux
Inkscape: ver 0.92.4-2

Any workaround?

**Comment by oxplot** [comment]
Can your friend view the PDF of the same SVG exported by Inkscape without the use of svglinkify?

**Comment by sunjerry019** [comment]
Yes, its viewable.

More specifically, if the file is exported using the following cli options, it is viewable no issues
`inkscape --file=$FILE.svg --export-area-page --without-gui --export-pdf=$FILE.pdf`
except the links don't work

((These are just the options I've been using for a few years now, nothing special about them))

[drawing.normalexport.pdf](https://github.com/oxplot/svglinkify/files/2805437/drawing.normalexport.pdf)

**Comment by oxplot** [comment]
Is svglinkify creating non-readable PDFs in Adobe reader for all exported SVGs or just your specific example? In other words, can you try a simple SVG and see if you still get a white page in  Adobe reader?

**Comment by sunjerry019** [comment]
I was actually working on another document, the document I've linked up there^ is specifically a simple test document. As you can see, it only has the text "Test Link" written in it. You can try it for yourself to see if you can reproduce the error.

**Comment by oxplot** [comment]
I've confirmed this. Seems like Adobe's reader thinks the file is corrupt.

**Comment by jedick** [comment]
A workaround is possible with [pdftk](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/). Run this command on the PDF generated by svglinkify:

`pdftk drawing.pdf cat 1 output drawing1.pdf`

drawing1.pdf can be viewed in Adobe Reader, and the link is active.

**Comment by fedebyes** [comment]
I can confirm the error too, unfortunately since I'm using that for my CV it makes it better to not use links and use plain text to avoid unreadability on Mac.

**Comment by oliverpool** [comment]
It seems that the latest version of inkscape now embeds the links automatically ! (v1.0 (4035a4fb49, 2020-05-01))

**Comment by oxplot** [comment]
> It seems that the latest version of inkscape now embeds the links automatically ! (v1.0 (4035a4fb49, 2020-05-01))

This is amazing news! Well, that marks the end of this project. Thanks for letting us know.
